MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,c,b){c||(c="load");b||(b=window);b.attachEvent?b.attachEvent("on"+c,a):b.addEventListener(c,a,false)}function json(a){try{return eval("("+a+")")}catch(c){return null}}function _180(a){if(!a||typeof a=="string")return a;var c="",b;for(b in a)c+="&"+b+"="+encodeURIComponent(a[b]);c&&(c=c.substr(1));return c}
function ajax(a){var c=/POST/i.test(a.type),b=a.data||"",d=a.dataType,f=a.url||location.href,e=/\?/.test(f)?"&":"?",g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(b){if(g.readyState==4)g.status==200?(b=g.responseText,d=="json"&&(b=json(b)),(c=a.success)&&c(b)):a.error&&a.error(g.status,g)};if(typeof b=="object"){var i=[],h;for(h in b)i.push(encodeURIComponent(h)+"="+encodeURIComponent(b[h]));b=i.join("&")}g.open(c?
"POST":"GET",f+(c?"":(b?e:"")+b+(a.cache?"":(!b&&e=="?"?"?":"&")+"_="+(new Date).getTime())),a.async===false?false:true);c&&g.setRequestHeader("Content-Type","application/x-www--urlencoded");g.send(b);return g}
var ajaxHelper=function(a){a=a||{};a.method=a.method||"GET";a.type=(a.type||"text").toLowerCase();a.jsonp_callback=a.jsonp_callback||"callback";a.success=a.success||function(){};a.error=a.error||function(){};a.cache_ok=a.cache_ok||false;a.url=a.url||(a.error({status:-5,desc:"Empty url"}),"");a.cache_ok||(a.url+=a.url.indexOf("?")>-1?"&":"?",a.url+="_mats="+(new Date).getTime(),a.url+="&callback="+a.jsonp_callback);if(a.type=="jsonp"){window[a.jsonp_callback]=function(b){a.success(b)};var c=document.getElementsByTagName("head")[0],
b=document.createElement("script");b.type="text/javascript";b.src=a.url;b.onload=function(){};b.onerror=function(){a.error({status:-2,desc:"Failed to load the url: "+a.url})};c.appendChild(b)}else{var d;window.XMLHttpRequest?d=new XMLHttpRequest:a.error({status:-3,desc:"Platform not supported"});d.onreadystatechange=function(){if(d.readyState==4)if(d.status==200){var b="ok",b=d.responseText;if(a.type=="json")try{b=JSON.parse(b),a.success(b)}catch(c){b=c.toString(),a.error({status:-6,desc:"Error in parsing JSON ("+
b+")"})}else a.type=="text"&&a.success(b)}else a.error({status:-4,desc:"Error in fetching data (code "+d.status+")"})};d.open(a.method,a.url,true);d.send()}};function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}
function fo(a){var c=0,b=0;do c+=a.offsetLeft||0,b+=a.offsetTop||0;while(a=a.offsetParent);return{x:c,y:b}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,c){for(var b=RegExp("(^|\\s*)"+a+"(\\s*|$)"),d=c?document.getElementsByTagName(c):document.getElementsByTagName("*")||document.all,f=[],e=0,g=d.length;e<g;e++)b.test(d[e].className)&&f.push(d[e]);return f}JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};
function getElementOffset(a){for(var c=0,b=0;a&&a.tagName!="BODY";)c+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:c,left:b}}
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if(a.id.indexOf("_stage")>0||a.getAttribute("data-mid")==0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=_mrmcp.display_mode,b=mraid.getPlacementType();this.mraidState=a.toLowerCase();var d=document.getElementById("mugeda_close_button");
switch(this.mraidState){case "default":if(c!="expand"&&b!="interstitial"&&d)d.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(c=="auto"||c=="expand"||c=="interstitial")&&setTimeout(function(){d.style.display="block"},50);break;case "resized":setTimeout(function(){d.style.display="block"},50)}},openLink:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=
_mrmcp.destination_url);var b="ts="+(new Date).getTime();b+="&_moid="+(_mrmcp.owner_id||"");b+="&_mcid="+(_mrmcp.creative_id||"");b+="&_mw="+(_mrmcp.width||"");b+="&_mh="+(_mrmcp.height||"");b+="&_mtp="+(_mrmcp.type||"");b+="&_mtt="+escape(_mrmcp.title||"");var d=_mrmcp.custom_params;d&&d.indexOf("%CUSTOMPARAM%")<0&&(b+="&"+d);if((d=_mrmcp.redirect_url)&&d.indexOf("%LINK%")<0)var f=a.indexOf("?"),f=f<0?"?":"&",a=d+(d.lastIndexOf("=")==d.length-1?escape(a+f+b):"");var f=a.indexOf("?"),d=f<0?"?":"&",
f=f==a.length-1,e=window.location.search;if(e){for(var e=e.split("?")[1],g=e.split("&"),i=g.length,h=0;h<i;h++){var j=g[h].split("=");if(j.length==2){var q=j[1];j[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(q),f=a.indexOf("?"),d=a<0?"?":"&",f=f==a.length-1)}}a+=(f?"":d)+e;f=false;e.length&&(d="&")}a+=(f?"":d)+b;this.mraidReadyStatus==1?c=="internal"?mraid.open(a):c=="expand"?this.expand(a,0):window.open(a):c=="internal"?window.location=a:c=="expand"?this.expand(a):window.open(a);MugedaTracker.fireEvent({category:"link",
action:c,label:a,value:0})},expand:function(a,c,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var d=document.URL.match(/client.*preview.*id/),f=b=null;try{b=(d?window:window.parent).document,f=b.getElementById("mugeda_expanded")||b.createElement("div")}catch(e){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||"")+a);f.id="mugeda_expanded";f.style.display="block";f.style.position="fixed";f.style.width=(b.defaultView.innerWidth||
b.documentElement.clientWidth)+"px";f.style.height=(b.defaultView.innerHeight||b.defaultView.innerHeight)+"px";f.style.left="0px";f.style.margin="0";f.style.padding="0";f.style.border="none";f.style.top="0px";f.style.background="#000";f.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;'></iframe>";b.body.appendChild(f);MugedaBehavior.processCloseButton("expand",b)}}else{var b=b||{},f=mraid.getMaxSize(),d=parseInt(b.width)||f.width,
f=parseInt(b.height)||f.height,a=a||b.url,g=!a||a.length==0;c==1?(a=parseInt(b.left)||0,b=parseInt(b.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:d,height:f,offsetX:a,offsetY:b,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:d,height:f,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),g?(mraid.expand(),MugedaBehavior.processCloseButton()):mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+
a.email_title+"&body="+a.email_body,"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(a,c){if(a){var b="_"+ +new Date,d=0,f=0;a.data&&(b="_"+a.data.guid,a.data.param&&
(d=a.data.param.continueAudio||0,f=a.data.param.clickStatus||0));var e=G("mugeda_video"+b);if(e)return e.parentNode;div=document.createElement("div");div.className="mugedaVideoHolder";div.style.margin=0;div.style.padding=0;div.style.backgroundColor="rgba(0,0,0,0.8)";div.style.position="absolute";div.style.top=0;div.style.left=0;div.style.width=0;div.style.height=0;div.style.zIndex=1;div.style.display="none";_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var g=(_mrmcp.creative_path||"")+"close_button.png",
i=navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i);div.innerHTML='<video id="mugeda_video'+b+'" preload="auto" webkit-playsinline="true" video-id="'+c.id+'"  video-mode="'+c.mode+'" video-name="'+c.name+'"  style="width:100%;height:100%;position:absolute;z-index:2;"></video>'+('<div id="mugeda_video_close'+b+'" align="middle" style="position: absolute;color:white;width:36px;height:36px;right:0px;top: '+(i?0:0)+"px;cursor:pointer;background-image: url("+g+');z-index:3;"></div>');
a.appendChild?a.appendChild(div):a.dom&&a.dom.appendChild(div);e=G("mugeda_video"+b);b=G("mugeda_video_close"+b);b.style.display=c.close_button?"block":"none";c.close_button&&(g=isMobile()?"touchend":"click",b.addEventListener(g,function(a){a.stopPropagation();e.src="";e.rawSrc="";e.load();div.style.display="none"},false));c.video_controls?e.setAttribute("controls","controls"):e.removeAttribute("controls");e.rawPlay=e.play;e.rawPause=e.pause;e.play=function(){e.paused&&(e.onplayed(),e.rawPlay())};
e.pause=function(){e.onpaused();e.rawPause()};e.onplayed=function(){if(d==0&&window.backgroundMusic)backgroundMusic.prevPlayStatus=backgroundMusic.playStatus,backgroundMusic.pause(),backgroundMusic.playStatus=0};e.onpaused=function(){if(d==0&&window.backgroundMusic&&backgroundMusic.prevPlayStatus==1)backgroundMusic.play(),backgroundMusic.playStatus=1,delete backgroundMusic.prevPlayStatus};e.onclick=function(a){a.preventDefault();a.stopPropagation();f===0?this.paused?this.play():this.pause():this.paused&&
this.play()};return div}},loadUrl:function(a){var c=a.id||(new Date).getTime(),b=a.url||"",d=a.left||0,f=a.top||0,e=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),i=a.before||null,h=a.style,j=a.scroll,q=a.parent,r=a.onload,k=a.onclose,o=a.position,t=a.close_position;if(!i&&!q){var u=typeof Mugeda!="undefined"&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&u&&
(u=getElementOffset(u),d+=u.left,f+=u.top)}var n=G(c);n||(n=document.createElement("div"),q?q.appendChild(n):i?i.parentNode.insertBefore(n,i):document.body.appendChild(n));n.id=c;n.style.margin=0;n.style.padding=0;n.style.backgroundColor="transparent";n.style.position=o?o:"fixed";n.style.top=0;n.style.left=0;n.style.width=0;n.style.height=0;switch(t){case "leftTop":t="left:4px;top:4px;";break;case "leftbottom":t="left:4px;bottom:4px;";break;case "rightbottom":t="right:4px;bottom:4px;";break;default:t=
"right: 4px;top: 4px;"}n.innerHTML="<iframe "+(j?"":"scrolling=no ")+'id="'+c+'_iframe" style="border:none; width:100%;height:100%; '+(j?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+c+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+t+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');n.style.display="none";n.style.top=f+"px";n.style.left=
d+"px";n.style.width=e+"px";n.style.height=g+"px";n.style.display="block";n.style.cssText+=h;G(c+"_iframe_close").style.display=a.close_button?"block":"none";setTimeout(function(){if(a.close_button)G(c+"_iframe_close").onclick=function(){n.style.display="none";G(c+"_iframe").src="about:blank";k&&k(n)}},100);setTimeout(function(){var a=G(c+"_iframe");a.src=b;if(r)try{a.onload=function(){r(a);a.onload=null}}catch(d){}},100);return n},playAudio:function(a,c){var b=false;if(!a||!a.audio_url||!a.audio_url.length)return false;
var d=typeof Mugeda!="undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];if(d){if(d.loop=parseInt(a.audio_loop)==1?true:false,d.play)if(d.webAudio)b=d.play(a.event=="click"||c?true:false);else if(a.event=="click"){try{d.pause(),d.currentTime=0}catch(f){}setTimeout(function(){d.play()},5)}else(d.playStatus!=1||c)&&setTimeout(function(){d.play();d.playStatus=1;b=true},10)}else{var d=new Audio,e=document.createElement("source"),g=a.audio_url.lastIndexOf("."),
g=a.audio_url.substring(g+1),i=true;switch(g){case "ogg":e.type="audio/ogg";break;case "mp3":e.type="audio/mpeg";break;default:i=false,console.log("Audio extension ("+g+") not supported.")}if(i){e.src=a.audio_url;d.appendChild(e);d.autoplay=false;d.preload="auto";d.load();var h=document.getElementById("mugeda_resource_loading");if(!h)h=document.createElement("img"),h.id="mugeda_resource_loading",h.style.position="fixed",h.style.right="2px",h.style.top="2px",h.style.display="block",h.src=(_mrmcp.creative_path||
"")+"loading.gif",document.body.appendChild(h);h.style.display="block";b=true;d.addEventListener("canplay",function(){h.style.display="none";d.play()},false);MugedaBehavior.localCache[a.audio_url]=d}}return b},playHTML5Video:function(a){var c=a.left||0,b=a.top||0,d=isNaN(a.width)?"100%":Math.max(0,a.width)+"px",f=isNaN(a.height)?"100%":Math.max(0,a.height)+"px",e=window.Mugeda&&Mugeda.getCanvas?Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&e&&!a.video_holder&&!isNaN(a.left)&&(e=getElementOffset(e),
c+=e.left,b+=e.top);var g=document.body;if(a.video_holder)if((e=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&e.scene){var g=a.video_holder,g=g.split("/"),i=a.video_object===1;g.length===2?(e=e.scene.getObjectByName(i?g[1]:g[0]),i?(g=e?e.scene.objectHash[g[0]]:null,a.url=g?g.data.param.videoUrl:a.url):g=e?e.scene.getObjectByName(g[1]):null):i?(g=e.scene.objectHash[a.video_holder],a.url=g?g.data.param.videoUrl:a.url):g=e.scene.getObjectByName(a.video_holder)}else{if(window.mugedaCss&&mugedaCss.magic&&
(e=document.getElementById(mugedaCss.magic+"stage")))g=a.video_holder,g=g.split("/").map(function(a){return"."+a}),(g=e.querySelectorAll(g.join(" ")))&&g.length&&(g=g[0])}else g=document.body;e=this.createHTML5VideoTag(g,a);e.style.top=b+"px";e.style.left=c+"px";e.style.width=d;e.style.height=f;e.style.display="block";var h=e.querySelector("video");h.src=a.url;h.rawSrc=a.url;h.load();setTimeout(function(){h.play();h.playing=true},10)},playVideo:function(a){a=a||{};if(!a.video_url)return false;if(this.mraidReadyStatus!=
1){var c=a.dom||document.querySelector('video[video-id="'+a.video_id+'"]');a.video_mode=="object"&&a.video_id&&c&&c.rawSrc==a.video_url||this.playHTML5Video({url:a.video_url,id:a.video_id||"",name:a.video_name||"",mode:a.video_mode||"",video_object:parseInt(a.video_object,10),video_holder:a.video_holder,left:parseInt(a.video_left,10),top:parseInt(a.video_top,10),width:parseInt(a.video_width,10),height:parseInt(a.video_height,10),close_button:parseInt(a.video_close,10)==1,video_controls:parseInt(a.video_controls,
10)==1,auto:parseInt(a.video_autoplay,10)==1})}else mraid.playVideo(a.video_url)},stopVideo:function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),c=0,b=a.length;c<b;c++){var d=a[c].querySelector("video");if(d)d.src="",d.rawSrc="",d.load();a[c]&&(a[c].style.display="none")}},controlVideo:function(a,c){var b=document.querySelector("#mugeda_video_"+a);if(b)if(c=="play")b.play();else if(c=="pause")b.pause();else{if(c=="stop")b.pause(),b.currentTime=0}else if((b=Mugeda.getMugedaObject?
Mugeda.getMugedaObject():null)&&b.scene)if(b=b.scene.objectHash[a]){var d=b.data.param;c==="play"&&MugedaMraid.playVideo({auto:d.videoAutoPlay,clickStatus:d.clickStatus,event_name:"",hidePlayIcon:d.hidePlayIcon,video_close:0,video_continue_audio:d.continueAudio,video_controls:d.hidePlayControls==1?0:1,video_holder:b.data.guid,video_left:0,video_mode:"object",video_name:d.name,video_object:1,video_top:0,video_url:d.videoUrl})}},sendShortMessage:function(a){window.open("sms:"+a.phone_number+"?body="+
a.sms_body,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
MugedaBehavior={localCache:{},shakeHash:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},nextPage:function(){typeof Mugeda!="undefined"&&Mugeda.nextPage&&Mugeda.nextPage()},prevPage:function(){typeof Mugeda!="undefined"&&Mugeda.prevPage&&Mugeda.prevPage()},gotoPage:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoPage&&Mugeda.gotoPage(a)},disablePage:function(){typeof Mugeda!="undefined"&&
Mugeda.disablePage&&Mugeda.disablePage()},enablePage:function(){typeof Mugeda!="undefined"&&Mugeda.enablePage&&Mugeda.enablePage()},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},
callback:function(a,c){if(window&&c.name&&c.name.length&&window[c.name])window[c.name](a,c.key,c.value)},map:function(a){var c=a.map_key.replace(/(\n|\r)/g,"+"),b=a.map_address.replace(/(\n|\r)/g,"+"),d=navigator.userAgent.toLowerCase().indexOf("android")>-1,f=parseInt(a.map_type,10),e=function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),b=0,c=a.length;b<c;b++)a[b]&&(a[b].style.display="none");(a=G("mugedaMap-mask"))?g(1):(a=document.createElement("div"),b=window._mrmcp&&_mrmcp.creative_path?
_mrmcp.creative_path+"loading.gif":"/images/loading.gif",a.id="mugedaMap-mask",a.className="mugedaMapControl",a.innerHTML='<p id="mugedaMap-title"><a id="mugedaMap-back">\u8fd4\u56de</a>\u4f4d\u7f6e\u4fe1\u606f</p><div id="mugedaMap-con"></div><div id="mugedaMap-loading"><div class="spinner"></div><style>.mugedaMapControl {position:absolute;left:0;top:0;height:100%;width:100%;z-index:999999;}.mugedaMapMaskVisible {-webkit-transition:transform 1s;transform:translate3d(-100%, 0, 0);-webkit-transform:translate3d(-100%, 0, 0);}.mugedaMapControl #mugedaMap-title {position:fixed;height:44px;line-height:44px;width:100%;text-align:center;z-index:1;background:rgba(255,255,255,.8);margin:0;}.mugedaMapControl #mugedaMap-con {height:100%;width:100%;}.mugedaMapControl #mugedaMap-back {position:absolute;left:5px;display:inline-block;height:100%;width:40px;cursor:pointer;}.mugedaMapControl #mugedaMap-loading {position:absolute;width:100%;height:100%;line-height:100%;left:0;top:44px;display:none;background:#fff;z-index:2;}.mugedaMapControl .spinner {position:absolute;width:20px;height:30px;left:50%;top:50%;margin:-50px 0 0 -10px;background-image:url('+
b+');background-repeat:no-repeat;background-size:contain;}.mugedaMapControl .spinner:after {content: "\u52a0\u8f7d\u4e2d ...";position:absolute;width:80px;left:-25px;top:120%;}</style>',document.body.appendChild(a),(a=G("mugedaMap-back"))&&a.addEventListener("click",function(a){a.stopPropagation();g(0)},false))},g=function(a){var b=G("mugedaMap-mask");b&&b.classList.toggle("mugedaMapMaskVisible",!a)},i=function(a){var b=G("mugedaMap-loading");if(b)b.style.display=a?"block":"none"},h,j,q=function(a,
b,c,d){h||(h=new BMap.Map("mugedaMap-con"));h.centerAndZoom(c||"\u5317\u4eac",11);h.addControl(new BMap.ZoomControl);j||(j=new BMap.LocalSearch(h,{renderOptions:{map:h,autoViewport:true},onSearchComplete:function(a){typeof d==="function"&&d.call(h,a)}}));b&&a?j.searchNearby(b,a):j.search(b)},r=function(a,b,c){if(f===0){var d=["http://api.map.baidu.com/getscript?type=quick&file=api&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0","http://api.map.baidu.com/getscript?type=quick&file=feature&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0"],
b=decodeURIComponent(b),a=decodeURIComponent(a);e();i(1);for(var g=0,c=0,h=d.length;c<h;c++){var j=document.createElement("script");j.src=d[c];j.onload=function(){++g===h&&q(a,b,"",function(a){a.getNumPois()===0&&alert("\u62b1\u6b49\uff0c\u6ca1\u6709\u641c\u7d22\u5230\u76f8\u5173\u4fe1\u606f");i(0)})};document.head.appendChild(j)}}else if(d="https://maps.google.com/maps?q="+(a+""+(b.length?"+near+"+b:""))+"&z=12",j=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||
[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false,c==1){if(c=document.getElementById("aMugedaGeoLocation"))c.href=d,d=document.createEvent("HTMLEvents"),d.initEvent("click",true,true),c.dispatchEvent(d)}else j&&j<6?window.location.href=d:window.open(d,"_blank")};if(!d&&b.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);
navigator.geolocation.getCurrentPosition(function(a){b=a.coords.latitude+","+a.coords.longitude;r(c,b,1)})}else r(c,b)},popupForm:function(a,c){function b(a,b){if(a&&b)return a.querySelector("#"+b)}function d(a){if(window.localStorage&&window.localStorage.getItem)return unescape(localStorage.getItem(a)||"");var b,c,d,f=document.cookie.split(";");for(b=0;b<f.length;b++)if(c=f[b].substr(0,f[b].indexOf("=")),d=f[b].substr(f[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a.toLowerCase())return unescape(d);
return""}function f(a,b){if(window.localStorage&&window.localStorage.getItem)try{localStorage.setItem(a,escape(b))}catch(c){console.info("Oops, localStorage full"),localStorage.clear(),localStorage.setItem(a,escape(b))}else{var d=new Date;d.setDate(d.getDate()+3);d=escape(b)+"; expires="+d.toUTCString();document.cookie=a.toLowerCase()+"="+d}}function e(a){var b=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(b)b.style.display=a?"":"none";return b?true:false}function g(a){if(c){var b=
function(a,b){Array.prototype.forEach.call(a,function(a,c){b(a,c)})};b(a.querySelectorAll(".popupFormInputBox input,.popupFormInputBox textarea"),function(a){a.value=""});b(a.querySelectorAll(".popupFormRadioList input,.popupFormCheckbox input"),function(a){a.checked=false});b(a.querySelectorAll(".popupFormSelectList select"),function(a){a.value=a.querySelector("option").getAttribute("value")})}else if(b=a.querySelector("form"),b.style.bottom=-b.offsetHeight+"px",a.style.background="rgba(0,0,0,0)",
setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},500),e(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height="100%"}var i=a.openTarget=="default"||a.openTarget=="frame"||a.openTarget=="page";if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&a.openTarget!="customizable"&&!i&&!a.url)){var i=document.documentElement.clientWidth,h=document.documentElement.clientHeight,j=[],q=function(b,c){var c=c||{},d=c.detail,f=c.form||(d?d.form:null),
d={item:d,form:f,title:a.title,hideItem:function(a){f&&f.elements[a]&&(f.elements[a].parentNode.style.display="none")},showItem:function(a){f&&f.elements[a]&&(f.elements[a].parentNode.style.display="block")}},c=document.createEvent("Events");c.initEvent(b,true,true);c.detail=d;window.dispatchEvent(c)};window.addEventListener("_mugedaFormChanged",function(a){q("mugedaFormChanged",a)});var r=a.items||[];window.popupFormFields=r;if(!a.html){var k="";c?(k+='<div class="popupFormContent">',a.title&&(k+=
'<div align="center" class="popupFormTitle"><h2>'+a.title+"</h2></div>")):(k+='<div align="center" class="popupFormTitle">',k+='<div class="title-col-2" align="center"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel"></div>',k+='<div class="title-col-6" align="center"><h2>'+(a.title||"&nbsp;")+"</h2></div>",k+='<div class="title-col-2" align="center"><input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>',k+="</div>",
k+='<div class="popupFormContent">');var o=navigator.userAgent.toLowerCase(),t=o.indexOf("android")>-1,u=parseFloat(o.slice(o.indexOf("android")+8)),n="",y=0,I={phone:"tel",input:"text"};t&&u<3&&(n="-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var A=c?"":":",o=0;o<r.length;o++){var l=r[o],x=(l.value||"").trim();if(x){for(var x=x.split("\n"),p=[],v=0;v<x.length;v++){var H=x[v].split("("),z=H[0],H=(H[1]||"").replace(/\)$/,"")||z,D=["FORMID",H,o,v].join("_");p[v]={id:D,
text:z,value:H}}x=p}D='id="popupFormField_'+o+'"';switch(l.type){case "radio":k+="<div "+D+' class="popupFormRadioList">';l.description&&(k+='<label class="inputlabel">'+l.description+(l.required?"*":"")+A+"</label>");k+='<div class="mformradio">';for(v=0;v<x.length;v++)p=x[v],z=d(p.id),k+='<label><input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="radio" name="'+l.id+'" value="'+
p.value+'" id="'+p.id+'" '+(z=="true"?"checked=checked":"")+" ><span "+(v==x.length-1?"":" style='border-right:1px solid "+a.background+"'")+">"+p.text+"</span></label>",j[p.id]=p.id;k+="</div></div>";break;case "checkbox":k+="<div "+D+' class="popupFormCheckbox">';l.description&&(k+='<label class="inputlabel">'+l.description+(l.required?"*":"")+A+"</label>");k+='<div class="mformcheck">';k+=l.rangeType==="vertical"?"<table>":"";for(v=0;v<x.length;v++)p=x[v],z=d(p.id),k+=l.rangeType==="vertical"?
'<tr><td><input type="checkbox" value="'+p.value+'" id="'+p.id+'" '+(z=="true"?"checked=true":"")+' ></td><td><label for="'+p.id+'" >'+p.text+"</label></td></tr>":'<input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="checkbox" name="'+l.id+'" value="'+p.value+'" id="'+p.id+'" '+(z=="true"?"checked=true":"")+' ><label for="'+p.id+'" >'+p.text+"</label>",j[p.id]=p.id;t&&u<3&&l.rangeType!=
"vertical"&&(y=6);k+=l.rangeType==="vertical"?"</table>":"";k+="</div></div>";break;case "select":k+="<div "+D+' class="popupFormSelectList">';l.description&&(k+='<label class="inputlabel text">'+l.description+(l.required?"*":"")+A+"</label>");k+='<select class="text" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" name="'+l.id+'" id="'+("_map_"+l.description)+'">';k+='<option value="">'+l.description+
"</option>";z=d(l.description);for(v=0;v<x.length;v++)p=x[v],k+='<option value="'+p.value+'" '+(z==p.value?"selected=selected":"")+">"+p.text+"</option>";k+="</select>";k+="</div>";j[l.description]="_map_"+l.description;break;case "textarea":k+="<div "+D+' class="popupFormInputBox">';k+='<label class="inputlabel inputlabel_area">'+l.description+(l.required?"*":"")+A+'</label><textarea name="'+l.id+'" id="_mcp_'+escape(l.description)+'" rows="4" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" style="resize:none; height:48px;">'+
(l.value.length?l.value:d(l.description))+"</textarea>";k+="</div>";j[l.description]="_mcp_"+escape(l.description);break;default:k+="<div "+D+' class="popupFormInputBox">',k+='<label class="inputlabel text">'+l.description+(l.required?"*":"")+A+'</label><input class="text" name="'+l.id+'" id="_mcp_'+escape(l.description)+'" type="'+(I[l.type]||l.type)+"\" onchange=\"var event = document.createEvent('Events');event.initEvent('_mugedaFormChanged', true, true);event.detail = this;window.dispatchEvent(event);\" value=\""+
(d(l.description)||l.value)+'" '+(c?'placeholder="'+l.description+'"':"")+">",k+="</div>",j[l.description]="_mcp_"+escape(l.description)}}c&&(k+='<div class="popupFormBtn"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">',k+='<input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>');k+="</div>";a.html=k}delete this.popupFormDiv;var m=this.popupFormDiv;if(!m){o=function(b){var b=b||".popupForm",d=1;if(/^rgba\(\d+,\s\d+,\s\d+,\s([0-9.]+)\)$/.exec(a.background))d=
RegExp.$1;d="<style>"+b+" {width:100%;font-size:"+a.fontSize+'px;font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+' * {font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+" form{position:absolute;width:100%;background-color:"+a.background+";}"+b+" *{margin:0;box-sizing:border-box;-webkit-appearance: none; -moz-appearance: none; appearance: value;}"+b+" .inputlabel{width:33%;height:28px;font-size:"+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:top;color:#000;}"+
b+" span{color:#333;}"+b+" label{color:#000;}"+b+" #popupFormField_0{padding-top:16px;}"+b+" .popupFormMask {position:absolute;left:0;top:0;width:100%;height:100%;background-color: "+a.background+"}"+b+" .popupFormContent {position:relative;padding-bottom:16px; background-color:#fff;opacity:"+d+";}"+b+" .popupFormTitle {width:100%;padding:20px 0;overflow:hidden;background-color: "+a.background+"}"+b+" h2 {font-weight:normal;font-size:"+(2+parseInt(a.fontSize))+"px;color:"+a.color+";}"+b+" h3{text-align:left;font-size:"+
a.fontSize+"px; font-weight: normal;color:"+a.color+";}"+b+" .popupFormInputBox{padding:8px 16px;text-align:left;}"+b+" .popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{width:67%;height:28px;border:1px solid "+a.background+";font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:top;border-radius:2px;}"+b+" .popupFormSelectList{padding:8px 16px 0;}"+b+" .popupFormRadioList{padding:8px 16px 0;}"+b+" .popupFormCheckbox{padding:8px 16px 0;}"+b+" .popupFormTitle input{border-width:0;cursor:pointer;font-size:"+
a.fontSize+"px;color:"+a.color+"}"+b+" .popupFormSubmit{border:none;background:none}"+b+" .popupFormCancel{background:none;border:none;}"+b+" .popupFormRadioList input{margin:0 5px 0 8px;}"+b+" .popupFormRadioList label{vertical-align:top;}"+b+" .mformradio {background-color:#EFEFEF;border:1px solid "+a.background+";overflow:hidden;display:inline-block;}"+b+" .mformradio label{float:left; min-width:48px;position:relative;}"+b+" .mformradio label span{text-align:center;padding:6px 8px;display:block;}"+
b+" .mformradio label input{position:absolute;width:100%;height:100%;margin:0;border:0;opacity:0;}"+b+" .mformradio input:checked + span{background-color:"+a.background+";color:#F7F7F7;}"+b+" .mformcheck{margin:0 0 8px;display:inline-block;}"+b+" .mformcheck input{"+n+"width:24px;height:24px;background-color:#EFEFEF;border:1px solid "+a.background+";vertical-align:middle;margin:3px 2px;}"+b+" .mformcheck input:checked{background-color:"+a.background+";}"+b+" .popupFormTitle .title-col-2 {float:left;width:20%;padding:0 ;text-align:center;}"+
b+" .popupFormTitle .title-col-6 {float:left;width:60%;padding:0 ;}"+b+" .popupFormTitle .title-col-2 input {font-size:"+(2+parseInt(a.fontSize))+"px;}"+b+" .mformcheck label{vertical-align:"+y+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}";c&&(d+=b+" .popupFormBtn {width:100%;padding:20px 0 0 0;text-align:center;}",d+=b+" .popupFormSubmit {width:90px;height:30px;color:"+a.color+";background-color:"+a.background+"}",d+=b+" .popupFormCancel {width:90px;height:30px;margin-right:15px;color:"+
a.color+";display:none;background-color:"+a.background+"}");d+="</style>";return d};if(!m){var J=a.openTarget=="backend"?"popupFormIframe":"_"+a.openTarget,m=document.createElement("div");m.style.display="none";m.className=c?"popupForm2":"popupForm";var B="";if(c)var C=function(b){for(var c={l:48,r:200},d=0,f=0,e=b.length;f<e;f++){for(var i=b[f],g=i.description.length,h=0,j=0;j<g;j++)h+=i.description[j].match(/[\u3400-\u9FBF]/)?2:1;d=Math.max(d,h)}d=d>8?8:d;b=a.fontSize*(d-4);d>4&&d<=8&&(c.l+=b,c.r-=
b);return c}(r),B=o(".popupForm2");else B=o();m.innerHTML='<form method="'+a.method+'" target="'+J+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe>'+B;!c&&!a.isCss?document.body.appendChild(m):(a.hwObj=C,a.iframeDiv=m,a.parentDom&&a.parentDom.appendChild(a.iframeDiv));this.popupFormDiv=m;m.form=m.childNodes[0];m.form.onclick=function(){};self=this;c||m.addEventListener(isMobile()?"touchend":"mouseup",function(a){if(!window.cardFrame){if(a.target==
m)g(m),self.popupFormDiv=null,a.stopPropagation();var b=a.target.nodeName.toLowerCase(),c=(a.target.type||"").toLowerCase();["input","textarea","select"].indexOf(b)>=0&&c!="checkbox"&&c!="submit"&&(a.target.focus(),t&&setTimeout(function(){a.target.scrollIntoView();a.target.scrollIntoViewIfNeeded&&a.target.scrollIntoViewIfNeeded()},500),a.stopPropagation());c=="button"&&a.stopPropagation()}});B=function(){function d(){var f=[],e=r;if(!c)e=window.popupFormFields;for(var i=0;i<e.length;i++){var h=e[i],
j=b(m,"popupFormField_"+i),l="",k=j.querySelectorAll("select");k.length==0&&(k=j.querySelectorAll("textarea"),k.length==0&&(k=j.querySelectorAll("input")));if(k.length==1)l=k[0].value||"";else if(k.length>1){for(var l=[],n=0;n<k.length;n++)if(j=k[n],j.checked&&(l.push(j.value),j.type=="radio"))break;l=l.join(",")}if(h.required&&!l){alert((h.description||"item")+" required");k[0].focus();return}if(l)switch(h.type){case "phone":if(!/^\d+$/.test(l)){alert((h.description||"Phone number")+" required");
k[0].focus();return}break;case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(l)){alert((h.description||"Email")+" required");k[0].focus();return}}a.openTarget==="default"?f.push(encodeURIComponent(h.description+"("+h.id+")")+"="+encodeURIComponent(l||"")):f.push(encodeURIComponent(h.id)+"="+encodeURIComponent(l||""))}if("popupFormIframe"==J)G("actionButton").value=a.pendingName;f=f.join("&");e=a.url+"?"+f;a.loadFinished=function(){g(m);self.popupFormDiv=null};if(a.openTarget=="customizable")e=
{callback:function(){a.msg&&alert(a.msg)},cancel:false},window.MugedaCard&&MugedaCard.finalizeCustomParameters&&MugedaCard.finalizeCustomParameters(f,e),e.cancel!==true&&e.callback(),a.loadFinished();else if(a.openTarget=="default"||a.openTarget=="page"||a.openTarget=="frame"||a.openTarget=="callback"){i="";e=0;if(window._mrmcp)i=window._mrmcp.creative_id||"";else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)i=Mugeda.data.crid;if(i==""&&/\/edit\/(\w+)\&?/.test(top.location.href))i=RegExp.$1,e=i.length<
16?1:2;else if(i==""&&/id=(\w+)\&?/.test(window.location.search))e=3,i=RegExp.$1;h=function(a,b,c){var c=c||"post",d=document.createElement("form"),f=document.createElement("iframe");d.setAttribute("method",c);d.setAttribute("action",a);a="__iframe"+Math.random()*1E4;f.setAttribute("id",a);f.setAttribute("name",a);d.setAttribute("target",a);f.style.width=0;f.style.height=0;f.style.display="none";f.addEventListener("load",function(){});a=0;for(c=b.length;a<c;a++){var e=b[a].split("="),i=e[0],e=e[1],
h=document.createElement("input");h.setAttribute("type","hidden");h.setAttribute("name",i);h.setAttribute("value",e);d.appendChild(h)}document.body.appendChild(d);document.body.appendChild(f);d.submit()};if(i&&/^[a-z\-]+\.mugeda\.com$/.test(window.location.hostname))window._mrmcp=window._mrmcp||{},h(_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform",(f+"&crid="+i+"&mode="+e).split("&")),a.msg&&alert(a.msg);a.openTarget=="callback"?a.callback&&window[a.callback]?(e={callback:function(){a.msg&&
alert(a.msg)},cancel:false},window[a.callback](f,e),MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0}),e.cancel!==true&&e.callback()):console.log("No callback function found. Skipping..."):a.openTarget=="frame"?a.callback&&a.callback():a.openTarget=="page"&&a.callback&&a.callback();a.loadFinished()}else try{window.open(e,J),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",
value:a.id?parseInt(a.id,36):0});a.msg&&alert(a.msg)}}catch(y){a.loadFinished(),alert("Form submission failed. Please try again. ")}}m.querySelector("#popupFormIframe").onload=null;for(l in j){var e=document.getElementById(j[l]);e&&(e.type=="checkbox"||e.type=="radio"?f(l,e.checked):f(l,e.value))}u<3?d():setTimeout(d,200);return false}}m.style.display="";m.form.innerHTML=a.html;if(a.id)m.form.id=a.id;var K=isMobile()?"touchstart":"click";m.form.querySelector("input[id=actionButton]").addEventListener(K,
B,false);m.style.display="";m.style.visibility="hidden";setTimeout(function(){q("mugedaFormInitialized",{form:m.form});m.style.visibility="visible"},200);setTimeout(function(){b(m,"popupFormCancel").addEventListener(K,function(){g(m);self.popupFormDiv=null},false)},500);C=m.querySelectorAll(".popupFormInput");for(o=0;o<C.length;o++)B=C[o],B.onfocus=onInputFocus,B.onblur=onInputBlur;var w;a.target?w=a.target.getBoundingClientRect():(C=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&a.isCss?
(i=C.adaption,w={left:Math.max(0,(window.Mugine?1:-1)*i.marginLeft),top:window.Mugine?0:Math.max(0,(window.Mugine?1:-1)*i.marginTop),width:Math.min(i.width,C.width),height:Math.min(i.height,C.height)}):w={left:0,top:0,width:i,height:h};document.body.style.overflowY="auto";if(e()){if(m.style.marginLeft=Math.max(2,w.left+document.documentElement.scrollLeft+(w.width-m.offsetWidth)/2)+"px",m.style.marginTop=Math.max(2,w.top+document.documentElement.scrollTop+(w.height-m.offsetHeight)/2)+"px",m.style.marginBottom=
"32px",m.offsetHeight+32>document.documentElement.scrollHeight&&(m.style.marginTop=parseInt(window.getComputedStyle?getComputedStyle(m).marginTop:m.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=m.offsetHeight+64+"px"}else if(m.style.position="relative",m.style.left=w.left+"px",m.style.top=w.top+"px",Math.max(2,w.top+(w.height-m.offsetHeight)/2),Math.max(2,w.left+(w.width-m.offsetWidth)/2),!c){var F=m.querySelector("form");F.style.bottom="-9999px";m.style.overflow="hidden";
setTimeout(function(){m.style.background="rgba(0,0,0,0)";m.style.width=w.width+"px";m.style.height="100%";F.style.webkitTransition="none";F.style.bottom=-F.offsetHeight+"px";setTimeout(function(){F.style.webkitTransition="all 500ms";F.style.bottom="0px";F.style.overflowY="auto";!c&&(m.style.background="rgba(0,0,0,0.3)")},1)},1)}}}},getPopupFormHeight:function(a){for(var c=a.items,b=0,d=0,f=c.length;d<f;d++){var e=c[d];switch(e.type){case "input":case "phone":case "email":b+=44;break;case "textarea":b+=
64;break;case "radio":b+=48;break;case "checkbox":e=e.value.split("\n").length;b+=32*e+8;break;case "select":b+=36;break;default:b+=44}}a.title&&(b+=60);b+=8;b+=50;b+=16;return b},processAction:function(a,c,b){var d=true;if(a.type=="pause")this.pause(a.param);else if(a.type=="play")this.resume(1);else if(a.type=="next")this.next();else if(a.type=="previous")this.previous();else if(a.type=="nextPage")this.nextPage();else if(a.type=="prevPage")this.prevPage();else if(a.type=="disablePage")this.disablePage();
else if(a.type=="enablePage")this.enablePage();else if(a.type=="gotoPage"){var f=a.param&&a.param.page_number?a.param.page_number:a.param,e=typeof f=="string"?f.split(";"):[];e.length>1&&(f=e[Math.floor(Math.random()*e.length)]);f=parseInt(f);this.gotoPage(f)}else if(a.type=="callback")this.callback(a.object,a.param);else if(a.type=="map")this.map(a.param);else if(a.type=="gotoAndPlay")f=a.param&&a.param.frame_number?a.param.frame_number:a.param,e=typeof f=="string"?f.split(";"):[],e.length>1&&(f=
e[Math.floor(Math.random()*e.length)]),f=parseInt(f),isNaN(f)&&(f=a.param&&a.param.frame_name?a.param.frame_name:"",f=Mugeda.mapFrameNameId[f],f=parseInt(f)+1),this.gotoAndPlay(f);else if(a.type=="gotoAndPause"||a.type=="gotoAndStop")f=a.param&&a.param.frame_number?a.param.frame_number:a.param,e=typeof f=="string"?f.split(";"):[],e.length>1&&(f=e[Math.floor(Math.random()*e.length)]),f=parseInt(f),isNaN(f)&&(f=a.param&&a.param.frame_name?a.param.frame_name:"",f=Mugeda.mapFrameNameId[f],f=parseInt(f)+
1),this.gotoAndPause(f);else if(a.type=="call")MugedaMraid.makePhoneCall(a.param);else if(a.type=="sms")MugedaMraid.sendShortMessage(a.param);else if(a.type=="email")MugedaMraid.sendEmail(a.param);else if(a.type=="video")MugedaMraid.playVideo(a.param);else if(a.type=="stopVideo")MugedaMraid.stopVideo(a.param);else if(a.type=="audio")a.param.event=c,d=a.restart,window.Mugeda&&Mugeda.getMugedaObject&&(f=Mugeda.getMugedaObject(),f=Math.floor(f.scene.currentId),a.unit&&a.unit.frameStart==f&&(d=true)),
d=MugedaMraid.playAudio(a.param,d);else if(a.type=="picture")MugedaMraid.savePicture(a.param);else if(a.type=="calendar")MugedaMraid.addCalendarEvent(a.param);else if(a.type=="expand")MugedaMraid.expand(a.param.url,0,a.param);else if(a.type=="resize")MugedaMraid.expand("",1,a.param);else if(a.type=="stopAudio")Mugeda.stopAudio&&Mugeda.stopAudio(a.param);else if(a.type=="stopAllAudio")Mugeda.stopAudioAll&&Mugeda.stopAudioAll();else if(a.type=="submitForm"){var g=a.param,f=a.mugeda,e=g.submit_object,
i=g.submit_target||0;window._mrmcp=window._mrmcp||{};var g=i==0?_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform":g.submit_url,h="",i=0;if(window._mrmcp)h=window._mrmcp.creative_id||"";else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)h=Mugeda.data.crid,i=3;if(h==""&&/\/edit\/(\w+)\&?/.test(top.location.href))h=RegExp.$1,i=h.length<16?1:2;else if(h==""&&/id=(\w+)\&?/.test(window.location.search))i=3,h=RegExp.$1;if(h){e=e.split(",");i="crid="+h+"&mode="+i;for(h=0;h<e.length;h++){var j=
e[h],q=f.scene.getObjectByName(j);(q=q?q.text||"":"")&&(i+="&"+j+"="+q)}g+="?"+i;ajaxHelper({url:g,type:"jsonp",jsonp_callback:"form_callback",success:function(a){parseInt(a.status)},error:function(){}})}}f="actoin_type="+a.type+"&refid="+(new Date).getTime();for(item in a.param)f+="&"+item+"="+a.param[item];c=="click"&&window.event&&window.event.stopPropagation&&window.event.stopPropagation();d&&b&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",action:a.param.event_name,label:f,
value:0})},processCloseButton:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=c,d=null;if(!b)try{window!=window.parent?(b=window.parent.document,d=window.frameElement):b=document}catch(f){b=document}if(b){var e=null;try{e=window.parent.document,e.getElementById("mugeda_expanded")||e.createElement("div")}catch(g){return}var i=a||_mrmcp.display_mode,h=MugedaMraid.mraidReadyStatus==1?mraid.getPlacementType():"default",j=b.getElementById("mugeda_close_button");if(!j)j=b.createElement("img"),
j.id="mugeda_close_button",j.style.cursor="pointer",j.style.zIndex=99999,j.style.display="block",j.style.position="fixed",j.style.right="0",j.style.top="0",j.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){b.body.removeChild(j);i=="interstitial"&&d&&d.parentNode.removeChild(d);var a=b.getElementById("mugeda_expanded");a&&b.body.removeChild(a)}}),b.body.appendChild(j);if(h=="interstitial"||i=="auto"||i=="resize"||i=="expand"||i=="interstitial")j.src=(_mrmcp.creative_path||"")+
"close_button.png",j.onerror=function(){j.style.display="none"},j.onload=function(){j.style.display=h=="interstitial"||i!="auto"?"block":"none"}}},setupMobileActionCallback:function(a){MugedaBehavior.actionCallback=a},setupMobileActions:function(a,c,b){function d(a){var b=navigator.userAgent.toLowerCase().indexOf("android")>-1,d=b?15:20,e=b?5:10,i=function(a,i,h,g){if(Math.sqrt(a*a+i*i+h*h)>=(g?d:e)){a=(new Date).getTime();i=a-(MugedaBehavior.lastHitTime||0);if(!MugedaBehavior.lastHitTime||i>200)MugedaBehavior.shakeNum++,
MugedaBehavior.lastHitTime=a;else if(i>1E3)MugedaBehavior.shakeNum=0;if(MugedaBehavior.shakeNum>=(b?1:2)){for(var j in MugedaBehavior.shakeHash){a=MugedaBehavior.shakeHash[j];for(i=0;i<a.length;i++)info=a[i],h=info.object,h=h.displayObject?h.displayObject.realVisible:true,info.callback&&h&&(MugedaBehavior.processAction(info.behavior,info.behavior.event,true),info.callback())}MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,c.event);MugedaBehavior.shakeNum=0}}},h=0,g=0,j=0;if(a.acceleration===
null||a.acceleration.x===void 0||a.acceleration.y===void 0||a.acceleration.z===void 0||a.acceleration.x===null||a.acceleration.y===null||a.acceleration.z===null){if(a.accelerationIncludingGravity)h=a.accelerationIncludingGravity.x,g=a.accelerationIncludingGravity.y,j=a.accelerationIncludingGravity.z,i(h,g,j,1)}else h=a.acceleration.x,g=a.acceleration.y,j=a.acceleration.z,i(h,g,j,0)}var f=a.dataRef||a.aniData,e=a.dom?a.dom:window,g=isMobile()?"touchstart":"mousedown",i=isMobile()?"touchend":"mouseup",
h=isMobile()?"touchmove":"mousemove",j=null,q=0,r=0,k=0,o=0,t=0,u=0,n=function(a,b){var c=o-q,d=t-r,e=null;if(u-k<2E3&&(Math.abs(c)>32||Math.abs(d)>32))c=Math.atan2(-d,c)*180/Math.PI,-22.5<c&&c<=22.5?e="slide_right":22.5<c&&c<=67.5?e="slide_right_up":67.5<c&&c<=112.5?e="slide_up":112.5<c&&c<=157.5?e="slide_left_up":157.5<c||c<=-157.5?e="slide_left":-157.5<c&&c<=-112.5?e="slide_left_down":-112.5<c&&c<=-67.5?e="slide_down":-67.5<c&&c<=-22.5&&(e="slide_right_down");d=b.slideHash?b.slideHash[e]||{}:{};
c=d.behavior||{};d=d.callback;e&&c.event==e&&(MugedaBehavior.processAction(c,c.event,true),d&&d(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,c.event));j=null;return e};if(c.event=="touch_start")a.touchstartBehavior=c,a.touchStartCallback=b;a.slideHooked||e.addEventListener(g,function(b){b.preventDefault();j=a;var c=b.targetTouches?b.targetTouches[0]:null;q=c?c.pageX:b.pageX;r=c?c.pageY:b.pageY;k=(new Date).getTime();a.touchstartBehavior&&a.touchstartBehavior.event=="touch_start"&&
a.dom&&a.dom.style.display!="none"&&(MugedaBehavior.processAction(a.touchstartBehavior,a.touchstartBehavior.event,true),a.touchStartCallback&&a.touchStartCallback(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,a.touchstartBehavior.event))});if(c.event=="touch_end")a.touchendBehavior=c,a.touchendCallback=b;if(c.event.indexOf("slide_")==0)a.slideHash=a.slideHash||{},a.slideHash[c.event]={behavior:c,callback:b};a.slideHooked||e.addEventListener(i,function(b){b.preventDefault();j=null;
var c=b.changedTouches?b.changedTouches[0]:null;o=c?c.pageX:b.pageX;t=c?c.pageY:b.pageY;u=(new Date).getTime();n(e,a)&&b.stopPropagation();a.touchendBehavior&&a.touchendBehavior.event=="touch_end"&&a.dom.style.display!="none"&&(MugedaBehavior.processAction(a.touchendBehavior,a.touchendBehavior.event,true),a.touchendCallback&&a.touchendCallback(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,a.touchendBehavior.event))});!a.slideHooked&&e.addEventListener(h,function(){});!a.slideHooked&&
!isMobile()&&window.addEventListener(i,function(b){if(j)o=b.pageX,t=b.pageY,u=(new Date).getTime(),b.preventDefault(),n(e,a)&&b.stopPropagation()});a.slideHooked=true;if(c.event=="shake"&&window.DeviceMotionEvent){if(!window.mugedaShakeHooked)MugedaBehavior.shakeNum=0,window.addEventListener("devicemotion",d,false),window.mugedaShakeHooked=true;if(g=a.aniData?a.aniData.guid:null)MugedaBehavior.shakeHash[g]||(MugedaBehavior.shakeHash[g]=[]),MugedaBehavior.shakeHash[g].push({object:a,callback:b,behavior:c})}}};
MugedaTracker={fireEvent:function(a){if(!window.location||!window.location.host){var a=(_mrmcp.track_bot||"http://cdn.mugeda.com/media/pages/track/track_20131030.html")+"?"+(_mrmma_var1||"var1=none")+"&"+(_mrmma_var2||"var2=none")+"&category="+a.category+"&action="+a.action+"&label="+encodeURIComponent(a.label)+"&value="+a.value+"&noninteraction="+a.noninteraction,c=document.createElement("iframe");c.id=_mrmcp.creative_id;c.src=a;c.style.display="none";c.style.width="1px";c.style.height="1px";document.body.appendChild(c)}else if(this.fireGAEvent(a.category,
a.action,a.label,a.value,a.noninteraction),this.fireMUEvent(a.category,a.action,a.label,a.value),window.mugedaGetCustomTracker&&(c=window.mugedaGetCustomTracker())){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=_mrmcp.custom_params,d=_mrmma_tags;b&&b.indexOf("%CUSTOMPARAM%")<0&&(d+="&"+b);c(d,a.category,a.action,a.label,a.value)}},fireGAEvent:function(a,c,b,d,f){typeof _gaq!="undefined"&&(_gaq.push(["_trackEvent",a,c,b,d,f]),typeof _ga_mugeda_use_custom!="undefined"&&_gaq.push(["custom._trackEvent",
a,c,b,d,f]))},fireMUEvent:function(a,c,b,d){typeof _mugeda_tracker!="undefined"&&_mugeda_tracker.trackEvent({action:c,category:a,label:b,value:d})}};
function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),s="mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$22){alert(e$$22.toString())}
function genSessionId(a){for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=Number(+new Date).toString(36),d=0,f="",e=c.length;d<a;d++)f+=c[Math.floor(Math.random()*e)];return b+f.toLowerCase()}Mugeda=window.Mugeda||{};
Mugeda.Analytics=function(a,c){var b=[],d=0;window._mrmcp=window._mrmcp||{};a=a||_mrmcp.impression_pixel||"http://cn-stat.mugeda.com/stats/c.gif";c=c||_mrmcp.eventUrl||a;this.setAccount=function(){};this.setCustomVar=function(a,c,d){a=a||0;b[a]&&delete b[a];b[a]={};b[a][c]=d||""};var f=function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,
c_end))}return""},e=function(){f("clientId");for(var a=[],c=0;c<b.length;c++)for(var d in b[c])a[c]=d+"="+encodeURIComponent(b[c][d]);return a.join("&")},g=function(){var a=location.pathname,b=/(?:\/animation\/edit)|(?:\/page\/edit)|(?:\/default\/preview\.html)|(?:\/client\/preview(?:_css3)?\.html)/;return!location.host||b.test(a)?false:true};this.trackPageview=function(b){if(g()){this.startTime=(new Date).getTime();var c=a,j=new Image,q=c.indexOf("?")!=-1?"&":"?",r=_mrmcp.title||window._mrmma_title,
k=+new Date,o=window.location.host,t=(_mrmcp.width||window._mrmma_width)+"x"+(_mrmcp.height||window._mrmma_height),u=window.location.href.slice(window.location.href.indexOf("/",8)),n=screen.width+"x"+screen.height,b=b||{};b.msv="0.1.0";b.msa="MU-A001";b.msh=o;b.mscs=t;b.msp=u;b.mssr=n;b.mssi=genSessionId(16);b.mscn=r;b.msct=k;b.crid=_mrmcp.creative_id||"";for(var y in b)b.hasOwnProperty(y)&&(this.setCustomVar(d,y,b[y]),d++);b=f("msuid");if(!b)r=b=genSessionId(32),k=new Date,k.setDate(k.getDate()+
3650),document.cookie="msuid="+escape(r)+(3650==null?"":";expires="+k.toGMTString())+"; domain=.mugeda.com; path=/";this.setCustomVar(d++,"msuid",b);b=e();j.src=c+q+("mst=1&"+b)}};this.trackEvent=function(a){if(g()){var b=new Image,d=c,f=d.indexOf("?")!=-1?"&":"?",r=e(),a=a||{},k=(new Date).getTime(),o=k-this.startTime,t=encodeURIComponent(a.action||"submit"),u=encodeURIComponent(a.categroy||"weika"),n=encodeURIComponent(a.label||""),a=parseInt(a.value)||0;b.src=d+f+r+"&mst=2&msts="+k+"&msetd="+o+
"&msen="+t+"&msev="+a+"&msec="+u+"&msel="+n}}};try{window._mugeda_tracker=new Mugeda.Analytics,_mugeda_tracker.trackPageview()}catch(e$$23){}
function createFontFaceStyle(a,c,b,d,f){var e="cloudfont-"+c;b&&(e+="-"+b);var g=document.getElementById(e),i=Object.prototype.toString.call(d)==="[object Array]"&&typeof f==="function",h=function(a){return(a=RegExp("[?&]"+a+"=([^&#]*)").exec(window.location.href))?a[1]:0};a.toLowerCase()=="simhei"?a='"Microsoft YaHei", "\u5fae\u8f6f\u96c5\u9ed1", SimHei, sans-serif':b&&(a+="-"+b);if(g)return i&&f(a),a;for(var b=(b=h("fontApiType"))?b:3,g=["eot","eot","woff","ttf","svg"],j=c.indexOf("?")>-1?"&":"?",
h=window.bd_version||h("v")||0,q=[],r=d&&d.length,k=0,o=0,t=function(){var b=document.createElement("style"),c="@font-face {font-family:'"+a+"';\nsrc:"+q[0]+";\nsrc:"+q.slice(1).join(",\n")+";}",c=document.createTextNode(c);b.id=e;b.type="text/css";b.appendChild(c);document.head.appendChild(b)},u=function(b){ajax({url:b,success:function(){++o===r&&typeof f==="function"&&(t(),f(a))},error:function(){if(--r===0)throw f(false),"request font failed";}})},n=0,y=g.length;n<y;n++){var I=c+j+"format="+g[n]+
"&api_type="+b+"&v="+h,A="url("+I+")";if(n>0){var l=g[n];g[n]==="eot"?l="embedded-opentype":g[n]==="ttf"&&(l="truetype");A+=" format('"+l+"')"}q.push(A);i&&d.indexOf(l)>-1&&(k++,u(I))}if(i){if(k===0)throw"request type invalid";}else t();return a};
